services:
  webserver:
    image: ghcr.io/ucfopen/materia:webserver-dev
    build:
      context: ../
      dockerfile: materia-webserver.Dockerfile
    ports:
      - "80:80" # main materia
      - "443:443" # main materia
    networks:
      - frontend
    depends_on:
      - app

  app:
    image: ghcr.io/ucfopen/materia:app-dev
    build:
      context: ../
      dockerfile: materia-app.Dockerfile
    environment:
      # View Materia README for env settings
      - AUTH_SALT=${DEV_ONLY_AUTH_SALT}
      - AUTH_SIMPLEAUTH_SALT=${DEV_ONLY_AUTH_SIMPLEAUTH_SALT}
      - BOOL_LTI_LOG_FOR_DEBUGGING=true
      - CIPHER_KEY=${DEV_ONLY_SECRET_CIPHER_KEY}
      - CRYPTO_HMAC=${DEV_ONLY_SECRET_CIPHER_KEY}
      - CRYPTO_IV=${DEV_ONLY_SECRET_CIPHER_KEY}
      - CRYPTO_KEY=${DEV_ONLY_SECRET_CIPHER_KEY}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}
      - USER_INSTRUCTOR_PASSWORD=${DEV_ONLY_USER_PASSWORD}
      - USER_STUDENT_PASSWORD=${DEV_ONLY_USER_PASSWORD}
      - USER_SYSTEM_PASSWORD=${DEV_ONLY_USER_PASSWORD}
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: materia_frontend
  backend:
    name: materia_backend

