version: '3.5'
# loaded by default unless you use docker-compose -f flag
# this is needed because we want test to mount throw-away file storage that doesn't affect your dev environment
# docker-compose won't let an override file define the same mount point.
# since this file is loaded by default except when using -f to load a different override, that avoids
# the problem of multiple mounts at the same point

services:
  webserver:
    volumes:
      - ../public:/var/www/html/public:ro
      - uploaded_widgets:/var/www/html/public/widget/:ro
      - ./config/nginx/key.pem:/etc/nginx/conf.d/key.pem:ro
      - ./config/nginx/cert.pem:/etc/nginx/conf.d/cert.pem:ro
      - ./config/nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro

  app:
    environment:
      # values sourced from docker/env
      - ASSET_STORAGE_DRIVER
      - ASSET_STORAGE_S3_CREDENTIAL_PROVIDER
      - ASSET_STORAGE_S3_BUCKET
      - ASSET_STORAGE_S3_ENDPOINT
      - ASSET_STORAGE_S3_KEY
      - ASSET_STORAGE_S3_SECRET
      - OPENAI_API_KEY
      - OPENAI_MODEL
      - OPENAI_ALLOW_IMAGES
    volumes:
      - ..:/var/www/html/
      - uploaded_widgets:/var/www/html/public/widget/
      - ./dockerfiles/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - fakes3
      - mysql
      - memcached

  mysql:
    environment:
      # values sourced from docker/env
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE

  fakes3:
    volumes:
      - uploaded_media:/s3mnt/fakes3_root/fake_bucket/media/

volumes:
  # static_files: {} # compiled js/css and uploaded widgets
  uploaded_media: {} # uploaded media files
  uploaded_widgets: {}
